/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceRouteImport } from './routes/_workspace'
import { Route as WorkspaceLabRouteImport } from './routes/_workspace/lab'
import { Route as WorkspaceShowcaseIndexRouteImport } from './routes/_workspace/showcase/index'
import { Route as WorkspaceShowcaseComponentRouteImport } from './routes/_workspace/showcase/$component'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/_workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceLabRoute = WorkspaceLabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceShowcaseIndexRoute = WorkspaceShowcaseIndexRouteImport.update({
  id: '/showcase/',
  path: '/showcase/',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceShowcaseComponentRoute =
  WorkspaceShowcaseComponentRouteImport.update({
    id: '/showcase/$component',
    path: '/showcase/$component',
    getParentRoute: () => WorkspaceRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lab': typeof WorkspaceLabRoute
  '/showcase/$component': typeof WorkspaceShowcaseComponentRoute
  '/showcase/': typeof WorkspaceShowcaseIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lab': typeof WorkspaceLabRoute
  '/showcase/$component': typeof WorkspaceShowcaseComponentRoute
  '/showcase': typeof WorkspaceShowcaseIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_workspace': typeof WorkspaceRouteWithChildren
  '/_workspace/lab': typeof WorkspaceLabRoute
  '/_workspace/showcase/$component': typeof WorkspaceShowcaseComponentRoute
  '/_workspace/showcase/': typeof WorkspaceShowcaseIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/lab' | '/showcase/$component' | '/showcase/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/lab' | '/showcase/$component' | '/showcase'
  id:
    | '__root__'
    | '/'
    | '/_workspace'
    | '/_workspace/lab'
    | '/_workspace/showcase/$component'
    | '/_workspace/showcase/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkspaceRoute: typeof WorkspaceRouteWithChildren
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace': {
      id: '/_workspace'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/lab': {
      id: '/_workspace/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof WorkspaceLabRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/showcase/': {
      id: '/_workspace/showcase/'
      path: '/showcase'
      fullPath: '/showcase/'
      preLoaderRoute: typeof WorkspaceShowcaseIndexRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/showcase/$component': {
      id: '/_workspace/showcase/$component'
      path: '/showcase/$component'
      fullPath: '/showcase/$component'
      preLoaderRoute: typeof WorkspaceShowcaseComponentRouteImport
      parentRoute: typeof WorkspaceRoute
    }
  }
}

interface WorkspaceRouteChildren {
  WorkspaceLabRoute: typeof WorkspaceLabRoute
  WorkspaceShowcaseComponentRoute: typeof WorkspaceShowcaseComponentRoute
  WorkspaceShowcaseIndexRoute: typeof WorkspaceShowcaseIndexRoute
}

const WorkspaceRouteChildren: WorkspaceRouteChildren = {
  WorkspaceLabRoute: WorkspaceLabRoute,
  WorkspaceShowcaseComponentRoute: WorkspaceShowcaseComponentRoute,
  WorkspaceShowcaseIndexRoute: WorkspaceShowcaseIndexRoute,
}

const WorkspaceRouteWithChildren = WorkspaceRoute._addFileChildren(
  WorkspaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkspaceRoute: WorkspaceRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
