// Поверхность зоны `ui` — примитивы поверх `@kobalte/core`.
//
// Вход ОДИН, подпутей нет. Причина не в лени: пакет объявляет `sideEffects: false` и ESM, а
// значит неиспользованный примитив выбрасывается сборщиком потребителя и без сегментации по
// подпутям. Подпути — это ещё и поверхность, каждая точка которой замерзает выпуском; заводим
// их, когда появится потребитель, которому корневого входа не хватило (`kb:PROBEWEB-4` —
// «не строить вперёд спроса»).
//
// Стилей отсюда не едет НИЧЕГО: у зоны нет CSS-артефакта, потому что нет и стилей по
// умолчанию. Оформление приезжает из `@omnifield/probe-web-style` и пишется потребителем.

export { Button, type ButtonProps } from "./button.jsx";
export {
  Checkbox,
  CheckboxControl,
  type CheckboxControlComponentProps,
  CheckboxDescription,
  type CheckboxDescriptionComponentProps,
  CheckboxError,
  type CheckboxErrorProps,
  CheckboxIndicator,
  type CheckboxIndicatorComponentProps,
  CheckboxInput,
  type CheckboxInputComponentProps,
  CheckboxLabel,
  type CheckboxLabelComponentProps,
  type CheckboxProps,
} from "./checkbox.jsx";
export {
  Combobox,
  ComboboxArrow,
  type ComboboxArrowComponentProps,
  ComboboxContent,
  type ComboboxContentComponentProps,
  ComboboxControl,
  type ComboboxControlComponentProps,
  ComboboxDescription,
  type ComboboxDescriptionComponentProps,
  ComboboxError,
  type ComboboxErrorProps,
  ComboboxHiddenSelect,
  ComboboxIcon,
  type ComboboxIconComponentProps,
  ComboboxInput,
  type ComboboxInputComponentProps,
  ComboboxItem,
  type ComboboxItemComponentProps,
  ComboboxItemDescription,
  type ComboboxItemDescriptionComponentProps,
  ComboboxItemIndicator,
  type ComboboxItemIndicatorComponentProps,
  ComboboxItemLabel,
  type ComboboxItemLabelComponentProps,
  ComboboxLabel,
  type ComboboxLabelComponentProps,
  ComboboxListbox,
  type ComboboxListboxComponentProps,
  ComboboxPortal,
  type ComboboxProps,
  ComboboxSection,
  type ComboboxSectionComponentProps,
  ComboboxTrigger,
  type ComboboxTriggerComponentProps,
} from "./combobox.jsx";
export {
  Dialog,
  DialogClose,
  type DialogCloseProps,
  DialogContent,
  type DialogContentComponentProps,
  DialogDescription,
  type DialogDescriptionComponentProps,
  DialogOverlay,
  type DialogOverlayComponentProps,
  DialogPortal,
  type DialogProps,
  DialogTitle,
  type DialogTitleComponentProps,
  DialogTrigger,
  type DialogTriggerComponentProps,
} from "./dialog.jsx";
export {
  DropdownMenu,
  DropdownMenuArrow,
  type DropdownMenuArrowComponentProps,
  DropdownMenuCheckboxItem,
  type DropdownMenuCheckboxItemComponentProps,
  DropdownMenuContent,
  type DropdownMenuContentComponentProps,
  DropdownMenuGroup,
  type DropdownMenuGroupComponentProps,
  DropdownMenuGroupLabel,
  type DropdownMenuGroupLabelComponentProps,
  DropdownMenuIcon,
  type DropdownMenuIconComponentProps,
  DropdownMenuItem,
  type DropdownMenuItemComponentProps,
  DropdownMenuItemDescription,
  type DropdownMenuItemDescriptionComponentProps,
  DropdownMenuItemIndicator,
  type DropdownMenuItemIndicatorComponentProps,
  DropdownMenuItemLabel,
  type DropdownMenuItemLabelComponentProps,
  DropdownMenuPortal,
  type DropdownMenuProps,
  DropdownMenuRadioGroup,
  type DropdownMenuRadioGroupComponentProps,
  DropdownMenuRadioItem,
  type DropdownMenuRadioItemComponentProps,
  DropdownMenuSeparator,
  type DropdownMenuSeparatorComponentProps,
  DropdownMenuSub,
  type DropdownMenuSubComponentProps,
  DropdownMenuSubContent,
  type DropdownMenuSubContentComponentProps,
  DropdownMenuSubTrigger,
  type DropdownMenuSubTriggerComponentProps,
  DropdownMenuTrigger,
  type DropdownMenuTriggerComponentProps,
} from "./dropdown-menu.jsx";
export {
  Field,
  FieldDescription,
  type FieldDescriptionProps,
  FieldError,
  type FieldErrorProps,
  type FieldProps,
  Input,
  type InputProps,
  Label,
  type LabelProps,
  Textarea,
  type TextareaProps,
} from "./field.jsx";
export {
  NumberField,
  NumberFieldDecrement,
  type NumberFieldDecrementProps,
  NumberFieldDescription,
  type NumberFieldDescriptionComponentProps,
  NumberFieldError,
  type NumberFieldErrorProps,
  NumberFieldHiddenInput,
  NumberFieldIncrement,
  type NumberFieldIncrementProps,
  NumberFieldInput,
  type NumberFieldInputComponentProps,
  NumberFieldLabel,
  type NumberFieldLabelComponentProps,
  type NumberFieldProps,
} from "./number-field.jsx";
export {
  Progress,
  ProgressFill,
  type ProgressFillComponentProps,
  ProgressLabel,
  type ProgressLabelComponentProps,
  type ProgressProps,
  ProgressTrack,
  type ProgressTrackComponentProps,
  ProgressValueLabel,
  type ProgressValueLabelComponentProps,
} from "./progress.jsx";
export {
  Popover,
  PopoverAnchor,
  type PopoverAnchorComponentProps,
  PopoverArrow,
  type PopoverArrowComponentProps,
  PopoverClose,
  type PopoverCloseProps,
  PopoverContent,
  type PopoverContentComponentProps,
  PopoverDescription,
  type PopoverDescriptionComponentProps,
  PopoverPortal,
  type PopoverProps,
  PopoverTitle,
  type PopoverTitleComponentProps,
  PopoverTrigger,
  type PopoverTriggerComponentProps,
} from "./popover.jsx";
export {
  RadioGroup,
  RadioGroupDescription,
  type RadioGroupDescriptionComponentProps,
  RadioGroupError,
  type RadioGroupErrorProps,
  RadioGroupItem,
  type RadioGroupItemComponentProps,
  RadioGroupItemControl,
  type RadioGroupItemControlComponentProps,
  RadioGroupItemDescription,
  type RadioGroupItemDescriptionComponentProps,
  RadioGroupItemIndicator,
  type RadioGroupItemIndicatorComponentProps,
  RadioGroupItemInput,
  type RadioGroupItemInputComponentProps,
  RadioGroupItemLabel,
  type RadioGroupItemLabelComponentProps,
  RadioGroupLabel,
  type RadioGroupLabelComponentProps,
  type RadioGroupProps,
} from "./radio-group.jsx";
export {
  Select,
  SelectContent,
  type SelectContentComponentProps,
  SelectIcon,
  type SelectIconComponentProps,
  SelectItem,
  type SelectItemComponentProps,
  SelectItemIndicator,
  type SelectItemIndicatorComponentProps,
  SelectItemLabel,
  type SelectItemLabelComponentProps,
  SelectListbox,
  type SelectListboxComponentProps,
  SelectPortal,
  type SelectProps,
  SelectTrigger,
  type SelectTriggerComponentProps,
  SelectValue,
  type SelectValueComponentProps,
} from "./select.jsx";
export {
  SegmentedControl,
  SegmentedControlDescription,
  type SegmentedControlDescriptionComponentProps,
  SegmentedControlError,
  type SegmentedControlErrorProps,
  SegmentedControlIndicator,
  type SegmentedControlIndicatorComponentProps,
  SegmentedControlItem,
  type SegmentedControlItemComponentProps,
  SegmentedControlItemControl,
  type SegmentedControlItemControlComponentProps,
  SegmentedControlItemDescription,
  type SegmentedControlItemDescriptionComponentProps,
  SegmentedControlItemIndicator,
  type SegmentedControlItemIndicatorComponentProps,
  SegmentedControlItemInput,
  type SegmentedControlItemInputComponentProps,
  SegmentedControlItemLabel,
  type SegmentedControlItemLabelComponentProps,
  SegmentedControlLabel,
  type SegmentedControlLabelComponentProps,
  type SegmentedControlProps,
} from "./segmented-control.jsx";
export { Separator, type SeparatorProps } from "./separator.jsx";
export { Skeleton, type SkeletonProps } from "./skeleton.jsx";
export {
  Slider,
  SliderDescription,
  type SliderDescriptionComponentProps,
  SliderError,
  type SliderErrorProps,
  SliderFill,
  type SliderFillComponentProps,
  SliderInput,
  SliderLabel,
  type SliderLabelComponentProps,
  type SliderProps,
  SliderThumb,
  type SliderThumbComponentProps,
  SliderTrack,
  type SliderTrackComponentProps,
  SliderValueLabel,
  type SliderValueLabelComponentProps,
} from "./slider.jsx";
export { Slot, type SlotProps } from "./slot.jsx";
export { Spinner, type SpinnerProps } from "./spinner.jsx";
export {
  Switch,
  SwitchControl,
  type SwitchControlComponentProps,
  SwitchDescription,
  type SwitchDescriptionComponentProps,
  SwitchError,
  type SwitchErrorProps,
  SwitchInput,
  type SwitchInputComponentProps,
  SwitchLabel,
  type SwitchLabelComponentProps,
  type SwitchProps,
  SwitchThumb,
  type SwitchThumbComponentProps,
} from "./switch.jsx";
export {
  Tabs,
  TabsContent,
  type TabsContentComponentProps,
  TabsIndicator,
  type TabsIndicatorComponentProps,
  TabsList,
  type TabsListComponentProps,
  type TabsProps,
  TabsTrigger,
  type TabsTriggerComponentProps,
} from "./tabs.jsx";
export {
  Toast,
  ToastClose,
  type ToastCloseProps,
  ToastDescription,
  type ToastDescriptionComponentProps,
  ToastList,
  type ToastListComponentProps,
  ToastProgressFill,
  type ToastProgressFillComponentProps,
  ToastProgressTrack,
  type ToastProgressTrackComponentProps,
  type ToastProps,
  ToastRegion,
  type ToastRegionComponentProps,
  ToastTitle,
  type ToastTitleComponentProps,
  toaster,
} from "./toast.jsx";
export { Toggle, type ToggleProps } from "./toggle.jsx";
export {
  ToggleGroup,
  ToggleGroupItem,
  type ToggleGroupItemComponentProps,
  type ToggleGroupProps,
} from "./toggle-group.jsx";
export {
  Tooltip,
  TooltipArrow,
  type TooltipArrowComponentProps,
  TooltipContent,
  type TooltipContentComponentProps,
  TooltipPortal,
  type TooltipProps,
  TooltipTrigger,
  type TooltipTriggerComponentProps,
} from "./tooltip.jsx";
