// Поверхность зоны `ui` — примитивы поверх `@kobalte/core`.
//
// Вход для примитивов ОДИН. Причина не в лени: пакет объявляет `sideEffects: false` и ESM, а
// значит неиспользованный примитив выбрасывается сборщиком потребителя и без сегментации по
// подпутям. Подпути — это ещё и поверхность, каждая точка которой замерзает выпуском; заводим
// их, когда появится потребитель, которому корневого входа не хватило (`PROBEWEB-4` —
// «не строить вперёд спроса»).
//
// Такой потребитель появился ровно один — и подпуть у зоны ровно один: `./passport` (`PWEB-2`).
// Паспорт читают механика скина и редактор, и им нужны ДАННЫЕ о частях, состояниях и оси
// вариаций, а не примитивы: через корневой вход перечень тянул бы за собой JSX, Solid и
// `@kobalte/core`. Отсюда же и обратное правило — ГОЛЫЙ паспорт из этого файла НЕ
// реэкспортируется: два входа к одним данным означали бы два обещания вместо одного.
//
// Правило про голый паспорт, и `KIT` его не нарушает (`PWEB-84`). Отсюда уезжает не второй
// перечень паспортов, а КАРТА — чем рисуется каждая часть, — и уезжает она вместе с паспортом
// одним значением, потому что порознь их нельзя ни проверить, ни применить. Дом у карты
// единственно возможный: значения в ней — компоненты Solid, а подпуть `./passport` продан как
// данные, читаемые без Solid и без браузера.
//
// Перечень паспортов не ведётся руками нигде: его ПОРОЖДАЕТ сборка, обходя папки компонентов
// (`scripts/build.mjs`). Файл, в который дописывает строку каждый новый компонент, — это общий
// владелец и очередь из овнеров; именно из таких файлов вырастает круг «один правит — ломается
// у второго». Перечень компонентов кита порождается тем же обходом и по той же причине.
//
// Стилей отсюда не едет НИЧЕГО: у зоны нет CSS-артефакта, потому что нет и стилей по
// умолчанию. Оформление приезжает из `@omnifield/probe-web-style` и пишется потребителем.

export {
  Accordion,
  AccordionItem,
  AccordionItemContent,
  type AccordionItemContentProps,
  AccordionItemIndicator,
  type AccordionItemIndicatorProps,
  type AccordionItemProps,
  AccordionItemTrigger,
  type AccordionItemTriggerProps,
  type AccordionProps,
} from "./accordion/index.js";
export {
  Checkbox,
  CheckboxControl,
  type CheckboxControlProps,
  CheckboxHiddenInput,
  type CheckboxHiddenInputProps,
  CheckboxIndicator,
  type CheckboxIndicatorProps,
  CheckboxLabel,
  type CheckboxLabelProps,
  type CheckboxProps,
} from "./checkbox/index.js";
export { Flow, FlowItem, type FlowItemProps, type FlowProps } from "./flow/index.js";
export { Grid, GridCell, type GridCellProps, type GridProps } from "./grid/index.js";
export { Icon, type IconProps } from "./icon/index.js";
export { Surface, type SurfaceProps } from "./surface/index.js";
export {
  Workspace,
  WorkspaceHeader,
  type WorkspaceHeaderProps,
  WorkspaceMain,
  type WorkspaceMainProps,
  type WorkspaceProps,
  WorkspaceRightbar,
  type WorkspaceRightbarProps,
  WorkspaceSidebar,
  type WorkspaceSidebarProps,
} from "./workspace/index.js";
// Карта частей вместе с паспортами (`PWEB-84`). Вход порождён сборкой обходом папок; форма пары
// и сверка ключей с анатомией — в `kit-form.ts`.
export {
  defineKitComponent,
  KIT,
  type KitComponent,
  kitOf,
  type PartComponent,
} from "./kit.js";
export {
  Collapsible,
  CollapsibleContent,
  type CollapsibleContentComponentProps,
  type CollapsibleProps,
  CollapsibleTrigger,
  type CollapsibleTriggerComponentProps,
} from "./collapsible.jsx";
export {
  AlertDialog,
  AlertDialogClose,
  type AlertDialogCloseProps,
  AlertDialogContent,
  type AlertDialogContentComponentProps,
  AlertDialogDescription,
  type AlertDialogDescriptionComponentProps,
  AlertDialogOverlay,
  type AlertDialogOverlayComponentProps,
  AlertDialogPortal,
  type AlertDialogProps,
  AlertDialogTitle,
  type AlertDialogTitleComponentProps,
  AlertDialogTrigger,
  type AlertDialogTriggerComponentProps,
} from "./alert-dialog.jsx";
// Компонент — это ПАПКА (разметка, анатомия, пробы рядом), и наружу из неё уезжает то, что
// назвал её собственный `index.ts`. Остальные примитивы переезжают в папки волной разноса
// (`PWEB-7`) — здесь они пока файлами.
export { Button, type ButtonProps } from "./button/index.js";
export {
  ColorArea,
  ColorAreaBackground,
  type ColorAreaBackgroundComponentProps,
  ColorAreaDescription,
  type ColorAreaDescriptionComponentProps,
  ColorAreaError,
  type ColorAreaErrorProps,
  ColorAreaHiddenInputX,
  ColorAreaHiddenInputY,
  ColorAreaLabel,
  type ColorAreaLabelComponentProps,
  type ColorAreaProps,
  ColorAreaThumb,
  type ColorAreaThumbComponentProps,
} from "./color-area.jsx";
export {
  ColorField,
  ColorFieldDescription,
  type ColorFieldDescriptionComponentProps,
  ColorFieldError,
  type ColorFieldErrorProps,
  ColorFieldInput,
  type ColorFieldInputComponentProps,
  ColorFieldLabel,
  type ColorFieldLabelComponentProps,
  type ColorFieldProps,
} from "./color-field.jsx";
export {
  ColorSlider,
  ColorSliderDescription,
  type ColorSliderDescriptionComponentProps,
  ColorSliderError,
  type ColorSliderErrorProps,
  ColorSliderInput,
  ColorSliderLabel,
  type ColorSliderLabelComponentProps,
  type ColorSliderProps,
  ColorSliderThumb,
  type ColorSliderThumbComponentProps,
  ColorSliderTrack,
  type ColorSliderTrackComponentProps,
  ColorSliderValueLabel,
  type ColorSliderValueLabelComponentProps,
} from "./color-slider.jsx";
// Единственная точка поверхности, которая не рендерит узел, а СТРОИТ значение: тип `Color` уже
// стоит в публичных пропах `ColorArea` и `ColorSlider`, а собрать его потребителю было нечем.
// Цена связи с `@kobalte/core` названа в `src/colors.ts` — там же основание (`PROBEWEB-4`).
export { type Color, parseColor } from "./colors.js";
export {
  Combobox,
  ComboboxArrow,
  type ComboboxArrowComponentProps,
  ComboboxContent,
  type ComboboxContentComponentProps,
  ComboboxControl,
  type ComboboxControlComponentProps,
  ComboboxDescription,
  type ComboboxDescriptionComponentProps,
  ComboboxError,
  type ComboboxErrorProps,
  ComboboxHiddenSelect,
  ComboboxIcon,
  type ComboboxIconComponentProps,
  ComboboxInput,
  type ComboboxInputComponentProps,
  ComboboxItem,
  type ComboboxItemComponentProps,
  ComboboxItemDescription,
  type ComboboxItemDescriptionComponentProps,
  ComboboxItemIndicator,
  type ComboboxItemIndicatorComponentProps,
  ComboboxItemLabel,
  type ComboboxItemLabelComponentProps,
  ComboboxLabel,
  type ComboboxLabelComponentProps,
  ComboboxListbox,
  type ComboboxListboxComponentProps,
  ComboboxPortal,
  type ComboboxProps,
  ComboboxSection,
  type ComboboxSectionComponentProps,
  ComboboxTrigger,
  type ComboboxTriggerComponentProps,
} from "./combobox.jsx";
export {
  ContextMenu,
  ContextMenuArrow,
  ContextMenuCheckboxItem,
  ContextMenuContent,
  ContextMenuGroup,
  ContextMenuGroupLabel,
  ContextMenuIcon,
  ContextMenuItem,
  ContextMenuItemDescription,
  ContextMenuItemIndicator,
  ContextMenuItemLabel,
  ContextMenuPortal,
  ContextMenuRadioGroup,
  ContextMenuRadioItem,
  ContextMenuSeparator,
  ContextMenuSub,
  ContextMenuSubContent,
  ContextMenuSubTrigger,
  ContextMenuTrigger,
} from "./context-menu.jsx";
export {
  Dialog,
  DialogClose,
  type DialogCloseProps,
  DialogContent,
  type DialogContentComponentProps,
  DialogDescription,
  type DialogDescriptionComponentProps,
  DialogOverlay,
  type DialogOverlayComponentProps,
  DialogPortal,
  type DialogProps,
  DialogTitle,
  type DialogTitleComponentProps,
  DialogTrigger,
  type DialogTriggerComponentProps,
} from "./dialog.jsx";
export {
  DropdownMenu,
  DropdownMenuArrow,
  type DropdownMenuArrowComponentProps,
  DropdownMenuCheckboxItem,
  type DropdownMenuCheckboxItemComponentProps,
  DropdownMenuContent,
  type DropdownMenuContentComponentProps,
  DropdownMenuGroup,
  type DropdownMenuGroupComponentProps,
  DropdownMenuGroupLabel,
  type DropdownMenuGroupLabelComponentProps,
  DropdownMenuIcon,
  type DropdownMenuIconComponentProps,
  DropdownMenuItem,
  type DropdownMenuItemComponentProps,
  DropdownMenuItemDescription,
  type DropdownMenuItemDescriptionComponentProps,
  DropdownMenuItemIndicator,
  type DropdownMenuItemIndicatorComponentProps,
  DropdownMenuItemLabel,
  type DropdownMenuItemLabelComponentProps,
  DropdownMenuPortal,
  type DropdownMenuProps,
  DropdownMenuRadioGroup,
  type DropdownMenuRadioGroupComponentProps,
  DropdownMenuRadioItem,
  type DropdownMenuRadioItemComponentProps,
  DropdownMenuSeparator,
  type DropdownMenuSeparatorComponentProps,
  DropdownMenuSub,
  type DropdownMenuSubComponentProps,
  DropdownMenuSubContent,
  type DropdownMenuSubContentComponentProps,
  DropdownMenuSubTrigger,
  type DropdownMenuSubTriggerComponentProps,
  DropdownMenuTrigger,
  type DropdownMenuTriggerComponentProps,
} from "./dropdown-menu.jsx";
export {
  Field,
  FieldDescription,
  type FieldDescriptionProps,
  FieldError,
  type FieldErrorProps,
  type FieldProps,
  Input,
  type InputProps,
  Label,
  type LabelProps,
  Textarea,
  type TextareaProps,
} from "./field.jsx";
export {
  NumberField,
  NumberFieldDecrement,
  type NumberFieldDecrementProps,
  NumberFieldDescription,
  type NumberFieldDescriptionComponentProps,
  NumberFieldError,
  type NumberFieldErrorProps,
  NumberFieldHiddenInput,
  NumberFieldIncrement,
  type NumberFieldIncrementProps,
  NumberFieldInput,
  type NumberFieldInputComponentProps,
  NumberFieldLabel,
  type NumberFieldLabelComponentProps,
  type NumberFieldProps,
} from "./number-field.jsx";
export {
  Progress,
  ProgressFill,
  type ProgressFillComponentProps,
  ProgressLabel,
  type ProgressLabelComponentProps,
  type ProgressProps,
  ProgressTrack,
  type ProgressTrackComponentProps,
  ProgressValueLabel,
  type ProgressValueLabelComponentProps,
} from "./progress.jsx";
export {
  Menubar,
  MenubarArrow,
  MenubarCheckboxItem,
  MenubarContent,
  MenubarGroup,
  MenubarGroupLabel,
  MenubarIcon,
  MenubarItem,
  MenubarItemDescription,
  MenubarItemIndicator,
  MenubarItemLabel,
  MenubarMenu,
  MenubarPortal,
  MenubarRadioGroup,
  MenubarRadioItem,
  MenubarSeparator,
  MenubarSub,
  MenubarSubContent,
  MenubarSubTrigger,
  MenubarTrigger,
} from "./menubar.jsx";
export {
  NavigationMenu,
  NavigationMenuArrow,
  NavigationMenuCheckboxItem,
  NavigationMenuContent,
  NavigationMenuGroup,
  NavigationMenuGroupLabel,
  NavigationMenuIcon,
  NavigationMenuItem,
  NavigationMenuItemDescription,
  NavigationMenuItemIndicator,
  NavigationMenuItemLabel,
  NavigationMenuMenu,
  NavigationMenuPortal,
  NavigationMenuRadioGroup,
  NavigationMenuRadioItem,
  NavigationMenuSeparator,
  NavigationMenuSub,
  NavigationMenuSubContent,
  NavigationMenuSubTrigger,
  NavigationMenuTrigger,
  NavigationMenuViewport,
} from "./navigation-menu.jsx";
export {
  Breadcrumbs,
  BreadcrumbsItem,
  type BreadcrumbsItemProps,
  BreadcrumbsLink,
  type BreadcrumbsLinkComponentProps,
  BreadcrumbsList,
  type BreadcrumbsListProps,
  type BreadcrumbsProps,
  BreadcrumbsSeparator,
  type BreadcrumbsSeparatorComponentProps,
  Image,
  ImageFallback,
  type ImageFallbackComponentProps,
  ImageImg,
  type ImageImgComponentProps,
  type ImageProps,
  Link,
  type LinkProps,
} from "./navigation.jsx";
export {
  Pagination,
  PaginationEllipsis,
  type PaginationEllipsisComponentProps,
  PaginationItem,
  type PaginationItemComponentProps,
  PaginationItems,
  PaginationNext,
  type PaginationNextComponentProps,
  PaginationPrevious,
  type PaginationPreviousComponentProps,
  type PaginationProps,
} from "./pagination.jsx";
export {
  Popover,
  PopoverAnchor,
  type PopoverAnchorComponentProps,
  PopoverArrow,
  type PopoverArrowComponentProps,
  PopoverClose,
  type PopoverCloseProps,
  PopoverContent,
  type PopoverContentComponentProps,
  PopoverDescription,
  type PopoverDescriptionComponentProps,
  PopoverPortal,
  type PopoverProps,
  PopoverTitle,
  type PopoverTitleComponentProps,
  PopoverTrigger,
  type PopoverTriggerComponentProps,
} from "./popover.jsx";
export {
  RadioGroup,
  RadioGroupDescription,
  type RadioGroupDescriptionComponentProps,
  RadioGroupError,
  type RadioGroupErrorProps,
  RadioGroupItem,
  type RadioGroupItemComponentProps,
  RadioGroupItemControl,
  type RadioGroupItemControlComponentProps,
  RadioGroupItemDescription,
  type RadioGroupItemDescriptionComponentProps,
  RadioGroupItemIndicator,
  type RadioGroupItemIndicatorComponentProps,
  RadioGroupItemInput,
  type RadioGroupItemInputComponentProps,
  RadioGroupItemLabel,
  type RadioGroupItemLabelComponentProps,
  RadioGroupLabel,
  type RadioGroupLabelComponentProps,
  type RadioGroupProps,
} from "./radio-group.jsx";
export {
  Select,
  SelectContent,
  type SelectContentComponentProps,
  SelectIcon,
  type SelectIconComponentProps,
  SelectItem,
  type SelectItemComponentProps,
  SelectItemIndicator,
  type SelectItemIndicatorComponentProps,
  SelectItemLabel,
  type SelectItemLabelComponentProps,
  SelectListbox,
  type SelectListboxComponentProps,
  SelectPortal,
  type SelectProps,
  SelectTrigger,
  type SelectTriggerComponentProps,
  SelectValue,
  type SelectValueComponentProps,
} from "./select.jsx";
export {
  SegmentedControl,
  SegmentedControlDescription,
  type SegmentedControlDescriptionComponentProps,
  SegmentedControlError,
  type SegmentedControlErrorProps,
  SegmentedControlIndicator,
  type SegmentedControlIndicatorComponentProps,
  SegmentedControlItem,
  type SegmentedControlItemComponentProps,
  SegmentedControlItemControl,
  type SegmentedControlItemControlComponentProps,
  SegmentedControlItemDescription,
  type SegmentedControlItemDescriptionComponentProps,
  SegmentedControlItemIndicator,
  type SegmentedControlItemIndicatorComponentProps,
  SegmentedControlItemInput,
  type SegmentedControlItemInputComponentProps,
  SegmentedControlItemLabel,
  type SegmentedControlItemLabelComponentProps,
  SegmentedControlLabel,
  type SegmentedControlLabelComponentProps,
  type SegmentedControlProps,
  SegmentedControlTrack,
  type SegmentedControlTrackProps,
} from "./segmented-control.jsx";
export { Separator, type SeparatorProps } from "./separator.jsx";
export { Skeleton, type SkeletonProps } from "./skeleton.jsx";
export {
  Slider,
  SliderDescription,
  type SliderDescriptionComponentProps,
  SliderError,
  type SliderErrorProps,
  SliderFill,
  type SliderFillComponentProps,
  SliderInput,
  SliderLabel,
  type SliderLabelComponentProps,
  type SliderProps,
  SliderThumb,
  type SliderThumbComponentProps,
  SliderTrack,
  type SliderTrackComponentProps,
  SliderValueLabel,
  type SliderValueLabelComponentProps,
} from "./slider.jsx";
export { Slot, type SlotProps } from "./slot.jsx";
export { Spinner, type SpinnerProps } from "./spinner.jsx";
export {
  Switch,
  SwitchControl,
  type SwitchControlComponentProps,
  SwitchDescription,
  type SwitchDescriptionComponentProps,
  SwitchError,
  type SwitchErrorProps,
  SwitchInput,
  type SwitchInputComponentProps,
  SwitchLabel,
  type SwitchLabelComponentProps,
  type SwitchProps,
  SwitchThumb,
  type SwitchThumbComponentProps,
} from "./switch.jsx";
export {
  Tabs,
  TabsContent,
  type TabsContentComponentProps,
  TabsIndicator,
  type TabsIndicatorComponentProps,
  TabsList,
  type TabsListComponentProps,
  type TabsProps,
  TabsTrigger,
  type TabsTriggerComponentProps,
} from "./tabs.jsx";
export {
  Toast,
  ToastClose,
  type ToastCloseProps,
  ToastDescription,
  type ToastDescriptionComponentProps,
  ToastList,
  type ToastListComponentProps,
  ToastProgressFill,
  type ToastProgressFillComponentProps,
  ToastProgressTrack,
  type ToastProgressTrackComponentProps,
  type ToastProps,
  ToastRegion,
  type ToastRegionComponentProps,
  ToastTitle,
  type ToastTitleComponentProps,
  toaster,
} from "./toast.jsx";
export { Toggle, type ToggleProps } from "./toggle.jsx";
export {
  ToggleGroup,
  ToggleGroupItem,
  type ToggleGroupItemComponentProps,
  type ToggleGroupProps,
} from "./toggle-group.jsx";
export {
  Tooltip,
  TooltipArrow,
  type TooltipArrowComponentProps,
  TooltipContent,
  type TooltipContentComponentProps,
  TooltipPortal,
  type TooltipProps,
  TooltipTrigger,
  type TooltipTriggerComponentProps,
} from "./tooltip.jsx";
