const MARKDOWN_PUNCTUATION = /([!"#$%&'()*+,./:;<=>?@[\\\]^_`{|}~-])/g;

export function escapeMarkdownText(value) {
  return String(value ?? '')
    .replace(/\r\n?|\n/g, ' ')
    .replace(MARKDOWN_PUNCTUATION, '\\$1')
    .replace(/\\:(?=\\\/\\\/)/g, `\\:\u200b`)
    .replace(/\bwww\\\./gi, (match) => match.replace('\\.', `\u200b\\.`))
    .replace(/\\@/g, `\\@\u200b`);
}

function summaryLines(summary) {
  return summary.map(({ label, value }) => `- **${label}:** ${escapeMarkdownText(value)}`);
}

function teamTable(team) {
  if (!team?.length) return [];

  return [
    '## Team Breakdown',
    '',
    '| Member | Hours | Entries | Avg/Day |',
    '| --- | ---: | ---: | ---: |',
    ...team.map(
      (member) =>
        `| ${escapeMarkdownText(member.name)} | ${escapeMarkdownText(member.hours)} | ${escapeMarkdownText(member.entries)} | ${escapeMarkdownText(member.average)} |`
    ),
    '',
    '---',
    '',
  ];
}

function entryLines(entries) {
  return entries.flatMap((entry) => [
    `### ${escapeMarkdownText(entry.heading)}`,
    '',
    ...entry.fields.map(({ label, value }) => `- **${label}:** ${escapeMarkdownText(value)}`),
    '',
    '---',
    '',
  ]);
}

export function buildTimeReportMarkdown(report) {
  const lines = [
    `# ${escapeMarkdownText(report.title)}`,
    '',
    `**Report Period:** ${escapeMarkdownText(report.period.from)} to ${escapeMarkdownText(report.period.to)}`,
    '',
    `**Generated:** ${escapeMarkdownText(report.generated)}`,
    '',
    '---',
    '',
    '## Summary',
    '',
    ...summaryLines(report.summary),
    '',
    '---',
    '',
    ...teamTable(report.team),
    '## Time Entries',
    '',
    ...entryLines(report.entries),
  ];

  if (report.totalSummary) {
    lines.push('## Total Summary', '', escapeMarkdownText(report.totalSummary), '', '---', '');
  }

  lines.push('*Generated by ostime Time Management System*', '');
  return lines.join('\n');
}
