import {
  Activity01Icon,
  Add01Icon,
  AiBrain01Icon,
  Alert01Icon,
  AttachmentIcon,
  Book01Icon,
  Calendar01Icon,
  Clock01Icon,
  ComputerIcon,
  CustomerSupportIcon,
  Database01Icon,
  File01Icon,
  Flag01Icon,
  FolderSearchIcon,
  GitMergeIcon,
  GridIcon,
  HierarchyIcon,
  Link01Icon,
  Mail01Icon,
  Message01Icon,
  Notification01Icon,
  PackageIcon,
  PaintBrush01Icon,
  PhoneCheckIcon,
  Plug01Icon,
  Search01Icon,
  Settings01Icon,
  Shield01Icon,
  Stamp01Icon,
  UserGroupIcon,
  WorkflowSquare01Icon,
} from '@hugeicons/core-free-icons';

export default {
  id: 'hugeicons',
  label: 'Hugeicons Free',
  license: 'MIT metadata · review required',
  mode: 'hugeicons',
  description:
    'Rounded 1.5px Hugeicons Free glyphs. Retained for visual comparison pending license clarification.',
  mainSize: 20,
  adminSize: 16,
  icons: {
    workspace: GridIcon,
    collections: FolderSearchIcon,
    time: Clock01Icon,
    milestones: Flag01Icon,
    iterations: Calendar01Icon,
    knowledge: Book01Icon,
    assets: PackageIcon,
    channels: CustomerSupportIcon,
    portal: Message01Icon,
    organizations: UserGroupIcon,
    teams: PhoneCheckIcon,
    create: Add01Icon,
    search: Search01Icon,
    settings: Settings01Icon,
    notifications: Notification01Icon,
    customFields: Database01Icon,
    screens: ComputerIcon,
    hierarchy: HierarchyIcon,
    itemTypes: File01Icon,
    priorities: Alert01Icon,
    statuses: WorkflowSquare01Icon,
    workflows: WorkflowSquare01Icon,
    approvals: Stamp01Icon,
    ai: AiBrain01Icon,
    scm: GitMergeIcon,
    integrations: Plug01Icon,
    links: Link01Icon,
    attachments: AttachmentIcon,
    themes: PaintBrush01Icon,
    mail: Mail01Icon,
    security: Shield01Icon,
    activity: Activity01Icon,
  },
};
