import {
  Activity,
  BadgeCheck,
  Bell,
  Blocks,
  Boxes,
  Building2,
  CalendarRange,
  ChartNoAxesGantt,
  CircleDotDashed,
  DatabaseZap,
  FileStack,
  GitPullRequestArrow,
  Goal,
  LibraryBig,
  Link2,
  Mail,
  MessagesSquare,
  Network,
  PackageOpen,
  PanelsTopLeft,
  Paperclip,
  Plus,
  RadioTower,
  Search,
  Settings2,
  Shapes,
  ShieldCheck,
  SignalHigh,
  Sparkles,
  SwatchBook,
  UsersRound,
  Workflow,
} from '@lucide/svelte';

export default {
  id: 'lucide-refined',
  label: 'Lucide refined',
  license: 'ISC',
  mode: 'lucide-refined',
  refined: true,
  description:
    'Curated Lucide metaphors with optical sizing, lighter resting strokes, and stronger selected-state containers.',
  mainSize: 18,
  adminSize: 15,
  icons: {
    workspace: PanelsTopLeft,
    collections: Boxes,
    time: ChartNoAxesGantt,
    milestones: Goal,
    iterations: CalendarRange,
    knowledge: LibraryBig,
    assets: PackageOpen,
    channels: RadioTower,
    portal: MessagesSquare,
    organizations: Building2,
    teams: UsersRound,
    create: Plus,
    search: Search,
    settings: Settings2,
    notifications: Bell,
    customFields: DatabaseZap,
    screens: Shapes,
    hierarchy: Network,
    itemTypes: FileStack,
    priorities: SignalHigh,
    statuses: CircleDotDashed,
    workflows: Workflow,
    approvals: BadgeCheck,
    ai: Sparkles,
    scm: GitPullRequestArrow,
    integrations: Blocks,
    links: Link2,
    attachments: Paperclip,
    themes: SwatchBook,
    mail: Mail,
    security: ShieldCheck,
    activity: Activity,
  },
};
