import {
  Activity,
  BadgeCheck,
  Bell,
  BookOpen,
  BrainCircuit,
  CalendarDays,
  Clock3,
  Database,
  FileText,
  Flag,
  Folder,
  GitBranch,
  GitFork,
  GitMerge,
  Headphones,
  LayoutGrid,
  Link,
  ListTree,
  Mail,
  MessageCircle,
  Monitor,
  Package,
  Paintbrush,
  Paperclip,
  Phone,
  Plug,
  Plus,
  Search,
  Settings,
  Shield,
  TriangleAlert,
  Users,
} from '@lucide/svelte';

export default {
  id: 'lucide',
  label: 'Lucide baseline',
  license: 'ISC',
  mode: 'lucide',
  description:
    'Untuned Lucide glyphs at their default 2px stroke, providing a control for the comparison.',
  mainSize: 20,
  adminSize: 16,
  icons: {
    workspace: LayoutGrid,
    collections: Folder,
    time: Clock3,
    milestones: Flag,
    iterations: CalendarDays,
    knowledge: BookOpen,
    assets: Package,
    channels: Headphones,
    portal: MessageCircle,
    organizations: Users,
    teams: Phone,
    create: Plus,
    search: Search,
    settings: Settings,
    notifications: Bell,
    customFields: Database,
    screens: Monitor,
    hierarchy: ListTree,
    itemTypes: FileText,
    priorities: TriangleAlert,
    statuses: GitBranch,
    workflows: GitFork,
    approvals: BadgeCheck,
    ai: BrainCircuit,
    scm: GitMerge,
    integrations: Plug,
    links: Link,
    attachments: Paperclip,
    themes: Paintbrush,
    mail: Mail,
    security: Shield,
    activity: Activity,
  },
};
